# Automatic Differentiation

In [12]:
import torch

# 2.5.1 A Simple Function

In [13]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [14]:
# Can also create x = torch.arange(4.0, requires_grad=True)
x.requires_grad_(True)
x.grad  # The gradient is None by default

In [15]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [16]:
y.backward()


In [17]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [18]:
x.grad == 4 * x

tensor([True, True, True, True])

In [19]:
print(x.grad)
x.grad.zero_()  # Reset the gradient
print(x.grad)
y = x.sum()
print(y)
y.backward()
print(y)
x.grad
print(x.grad)

tensor([ 0.,  4.,  8., 12.])
tensor([0., 0., 0., 0.])


tensor([1., 1., 1., 1.])